---
name: CI
# yamllint disable-line rule:truthy
on:
  push:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Install latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run ruff format
        run: uv run ruff format --check
      - name: Run ruff check
        run: uv run ruff check
      - name: Run yamllint
        run: git ls-files '*.yml' '*.yaml' | xargs uv run yamllint -s

  typecheck:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Install latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run mypy
        run: uv run mypy --config-file pyproject.toml -p arcticsecurity
      - name: Run ty
        run: uv run ty check

  pytest:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: read
    needs:
      - lint
      - typecheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Install latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run pytest
        run: uv run pytest --doctest-modules
